### ISSUE TITLE
Issues creating a Bluesky post

### ISSUE THREAD

**Issue by matthewstreeter** [jdhitsolutions/PSBluesky#15]
Hey Jeff! I reached out on Bluesky about this but I'm trying to get things setup with your module. I am having trouble getting the create post function to work for me however.

I'm able to from Get-BskyProfile, Get-BskyFollowers, etc. without an issue.

![New-BskyPost_Error](https://github.com/user-attachments/assets/dd5b39e6-94a0-4f45-a5fc-e9a0d9b26835)

**Comment by jdhitsolutions** [comment]
You need to specify the credential when you post, unless you set a PSDefaultParameterValue. Try again and include the -Credential parameter.

**Comment by jdhitsolutions** [comment]
I see that now. You can run `Get-BskyProfile` and it returns your profile using the Credential stored in $PSDefaultParameterValues. That tells us the credential is good and configured properly. Can you run any of the other `Get` commands in the module?

**Comment by jdhitsolutions** [comment]
Let's confirm that you are running on a Windows platform.

**Comment by jdhitsolutions** [comment]
Ok. That's a good sign. I don't think the Mac should make a difference,  but now I know I should at least test from Linux. Let's see if the information stream gives us any more data.  Re-run the post command and add `-InformationVariable iv`

Assuming the command fails, run `$iv.messagedata | format-list` and paste the results.

**Comment by matthewstreeter** [comment]
PS /Users/matthew/Documents/Scripting> $iv.MessageData | Format-List                                       
{
  "record": {
    "$type": "app.bsky.feed.post",
    "text": "Test posting to Bluesky via PSBluesky module from VSCode",
    "createdAt": "2024-11-11T15:08:32.7856370-06:00"
  },
  "collection": "app.bsky.feed.post",
  "repo": "matthewrstreeter.com"
}


![Screenshot 2024-11-11 at 3 09 43 PM](https://github.com/user-attachments/assets/8c8e4e07-d612-4598-9210-c06ac86ed6fd)

**Comment by jdhitsolutions** [comment]
That is what I would expect to see up until the error. I'm assuming the repo value matches your credential username including casing.

The error message sounds like a DNS-type problem, but that doesn't make sense since the other commands work. I am puzzled and don't have an immediate solution. I'll have to think about how else to troubleshoot.

**Comment by matthewstreeter** [comment]
Yes very odd but I was wondering if it might be DNS. My account is only a few days old. 

Would using my non custom domain Bluesky username be something to try potentially?

**Comment by jdhitsolutions** [comment]
I'm using a custom domain name without issue. I was able to post from Linux. You've posted content so that shouldn't be an issue. Let's try another approach.

```powershell
#use whatever variable name you are using for the credential object.
$repo = $cred.UserName
$pw = $cred.GetNetworkCredential().Password
$PDSHOST = 'https://bsky.social'
$headers = @{
    'Content-Type' = 'application/json'
}
$body = @{
    'identifier' = $user
    'password'   = $pw
} | ConvertTo-Json

$s = Invoke-RestMethod -Uri "$PDSHOST/xrpc/com.atproto.server.createSession" -Method Post -Headers $headers -Body $body
$token = $s.accessJwt
$headers = @{
    'Authorization' = "Bearer $token"
    'Content-Type'  = 'application/json'
}
$url = "$PDSHost/xrpc/com.atproto.repo.listRecords?repo=$repo&collection=app.bsky.feed.post&limit=5"
$r = Invoke-RestMethod -Uri $url -Method Get -Headers $headers

#this should return the last 5 posts
$r.records.value
```

Maybe this will validate the repo name.

**Comment by jdhitsolutions** [comment]
I don't think you finished setting up the verification for your custom name. https://bsky-debug.app/handle?handle=%40matthewrstreeter.com

**Comment by jdhitsolutions** [comment]
Never mind. I screwed that up.

**Comment by jdhitsolutions** [comment]
![image](https://github.com/user-attachments/assets/7d49bcea-2c88-4718-accf-50ee0918d57a)

**Comment by jdhitsolutions** [comment]
Also run: `(get-bskysession).diddoc` and let's see what you get. It should look like

```text
@context           : {https://www.w3.org/ns/did/v1, https://w3id.org/security/multikey/v1,
                     https://w3id.org/security/suites/secp256k1-2019/v1}
id                 : did:plc:ohgsqpfsbocaaxusxqlgfvd7
alsoKnownAs        : {at://jdhitsolutions.com}
verificationMethod : {@{id=did:plc:ohgsqpfsbocaaxusxqlgfvd7#atproto; type=Multikey;
                     controller=did:plc:ohgsqpfsbocaaxusxqlgfvd7;
                     publicKeyMultibase=zQ3sheWesAS13yhm6HYUwLqhZoBLHfWuT721feVqbVFR3w7hP}}
service            : {@{id=#atproto_pds; type=AtprotoPersonalDataServer;
                     serviceEndpoint=https://amanita.us-east.host.bsky.network}}
```

**Comment by matthewstreeter** [comment]
I'm back at my desk now. I'll give the code block a shot in a moment.

Here is the (Get-BskySession).diddoc output:
`PS /Users/matthew/Documents/Scripting> (Get-BskySession).diddoc

@context           : {https://www.w3.org/ns/did/v1, https://w3id.org/security/multikey/v1, 
                     https://w3id.org/security/suites/secp256k1-2019/v1}
id                 : did:plc:6sa7bzdm7behw6k45oaprg7f
alsoKnownAs        : {at://matthewrstreeter.com}
verificationMethod : {@{id=did:plc:6sa7bzdm7behw6k45oaprg7f#atproto; type=Multikey; 
                     controller=did:plc:6sa7bzdm7behw6k45oaprg7f; 
                     publicKeyMultibase=zQ3shkW3pzC8TyxNmCeror2d4PCrx3bA6vcJiH9jz3ykf93vq}}
service            : {@{id=#atproto_pds; type=AtprotoPersonalDataServer; 
                     serviceEndpoint=https://velvetfoot.us-east.host.bsky.network}}`

**Comment by jdhitsolutions** [comment]
The session looks right, which shouldn't be a surprise since most of the module commands work.

**Comment by jdhitsolutions** [comment]
A Bluesky user confirmed no problems using a Mac so the issue is something about your account.  I think this means creating the credential with your pre-custom name. First, try to get your profile with the old name. I'm not sure it will work.

**Comment by matthewstreeter** [comment]
I think I did things as instructed here. I stored my Bsky pass in a variable.

![Screenshot 2024-11-11 at 4 29 41 PM](https://github.com/user-attachments/assets/ff12570a-5aeb-4ae0-96ed-b2371903500a)

**Comment by jdhitsolutions** [comment]
That's the same problem. The repo is your username, which is getting pulled from the credential. I don't understand why the repo endpoint can't find the name.

**Comment by matthewstreeter** [comment]
My non-custom domain profile url still loads

Unfortunately no luck getting authenticated unless I did something wrong in my quick attempt.

![Screenshot 2024-11-11 at 4 40 29 PM](https://github.com/user-attachments/assets/0e563c7b-3ce2-4be2-bcdf-0633dfbd20ff)

**Comment by jdhitsolutions** [comment]
I stripped everything down to the bare essentials in this script file.

```powershell
Param(
    [PSCredential]$Credential
)

$message = "This is a debug test Bluesky message sent from VSCode."

$user = $credential.UserName
$pw = $credential.GetNetworkCredential().Password
$PDSHOST = 'https://bsky.social'

#create a session
$headers = @{'Content-Type' = 'application/json'}
$body = @{
    'identifier' = $user
    'password'   = $pw
} | ConvertTo-Json

$s = Invoke-RestMethod -Uri "$PDSHOST/xrpc/com.atproto.server.createSession" -Method Post -Headers $headers -Body $body
$headers.Add('Authorization', "Bearer $($s.accessJwt)")

$apiUrl = "$PDSHOST/xrpc/com.atproto.repo.createRecord"
$record = [ordered]@{
    '$type'   = 'app.bsky.feed.post'
    text      = $Message
    createdAt = (Get-Date -Format 'o')
}
$body = @{
    repo       = $Credential.UserName
    collection = 'app.bsky.feed.post'
    record     = $record
} | ConvertTo-Json -Depth 7

Invoke-RestMethod -Uri $apiUrl -Method Post -Headers $headers -Body $body -Verbose
```

Save this as a .ps1 file. Then run `script-fullname.ps1 $YourCredential` and see if it runs without errors. It just worked for me in VSCode.  Is your credential user name `matthewrstreeter` or `matthewrstreeter.com`?

**Comment by matthewstreeter** [comment]
Tried from my Windows machine with the same results bummer!

![image](https://github.com/user-attachments/assets/d9387f07-43c0-44c3-bf05-562fe2703e83)

**Comment by matthewstreeter** [comment]
I posted before seeing your recent post. I'll give that a try.

# Store credential in SecretManagement
$username = 'matthewrstreeter.com'

**Comment by jdhitsolutions** [comment]
That is what I would expect and since the other commands work, I didn't think that should be a problem.

**Comment by thedavecarroll** [comment]
I initially had the same issue.

- My login account is `user@thedavecarroll.com`
- My handle is `@thedavecarroll.com`
  - actually dropping the `@` worked.

Running 7.4.6 on MacOS 14.7.1.

Instead of using the email account I use to login to Bluesky, I used my `did` and that worked, as did my domain name.

I can run more commands later tonight if needed.

Might be worth mentioning that an entity could use subdomains die multiple people using the `.well-known` non-DNS method as mentioned in [How can I set and manage multiple subdomain handles?](https://bsky.social/about/blog/4-28-2023-domain-handle-tutorial).

**Comment by matthewstreeter** [comment]
Just tried this from my Windows system 

![image](https://github.com/user-attachments/assets/3342e3d2-64f3-4504-b27c-603956ba2054)

**Comment by jdhitsolutions** [comment]
@thedavecarroll  When you define your credential for use with this module, what do you set for the username?

**Comment by thedavecarroll** [comment]
I used:

- `dave@thedavecarroll.com`
  - failed
  - my login
- `@thedavecarroll.com`
  - failed
- `did:plc:rlwd5iajr3btl5e7gyvfwk67`
  - succeeded
- `thedavecarroll.com`
  - succeeded

**Comment by thedavecarroll** [comment]
This helped me.

https://bsky-debug.app/handle

**Comment by matthewstreeter** [comment]
I tried the did:xyzabc value for the repo and that was the trick (at least from my Windows machine so far)

![image](https://github.com/user-attachments/assets/95a3fe21-5790-4566-b25b-5058788ab295)

@thedavecarroll thanks for posting that the DID value worked for you.

**Comment by matthewstreeter** [comment]
I created a new Bluesky test account without a custom domain (matthew-test.bsky.social). 

I saw the same error posting to that on my Mac system but I had success posting on my Windows system.

![Screenshot 2024-11-13 at 8 28 16 PM](https://github.com/user-attachments/assets/a7675f44-44ff-4f92-bf84-e2ddb7b71047)

**Comment by jdhitsolutions** [comment]
I think we've narrowed down the problem is OS-related. The module works fine on Windows. And it mostly works on a Mac except for posting a message. This is going to take some external research.

**Comment by jdhitsolutions** [comment]
Does the Mac do any sort of proxy filtering?

**Comment by matthewstreeter** [comment]
It’s actually a brand new Mac Mini (yay me haha). Nothing customized for network or routing on this system either.

I can try from my work Mac too just to see if  the results are the same.

Matthew Streeter
Associate Manager, Enterprise Identity

Office: (913) 285-8080
Mobile: (916) 597-3233
IT Service Desk: (916) 573-5555 | ticket.powerschool.com

PowerSchool
Field Kansas | Central Time Zone
________________________________

**Comment by matthewstreeter** [comment]
Well... I was just successful posting from my work Mac. I'm wondering if the install of the module on my personal Mac went wonky or I happened to mess that up.

**Comment by jdhitsolutions** [comment]
Curious. I'm assuming the same version of PowerShell is installed on both.  Was your work Mac on the same network as the Mac Mini?  I can't imagine what you would have messed up installing the module.

**Comment by jdhitsolutions** [comment]
That is odd and frustrating because we're running out of things to test. I'm assuming PowerShell commands and other modules work just fine on the mini.

**Comment by jdhitsolutions** [comment]
Can you do any type of network capture like Wireshark to compare the `New-BskyPost` on each system?

**Comment by matthewstreeter** [comment]
I can post to my test account from my Mac Mini actually. It seems to be specific to my username as I cannot seem to use the New-BskyPost cmdlet for my 'matthewrstreeter.com' handle but I can post to my 'matthew-test.bsky.social' handle from any of my Macs.

Nothing on the Mac Mini for VPN or Private Relay either. Just rebooted too just be sure there 😄

**Comment by matthewstreeter** [comment]
From my Mac Mini trying to post to my test account first and then my primary account.

![image](https://github.com/user-attachments/assets/107b457d-0629-4a04-b63e-2e756869f145)

**Comment by jdhitsolutions** [comment]
I'm curious if the debug web page shows different results. I'm expecting if you open `https://bsky-debug.app/handle?handle=matthew-test.bsky.social` in a browser on both systems that they will show the same thing.  Is the same true when opening `https://bsky-debug.app/handle?handle=matthewrstreeter.com` ?

**Comment by matthewstreeter** [comment]
Yessir. Both links output the same results on both Macs.

Mac Mini
![image](https://github.com/user-attachments/assets/75828e95-b18c-45f1-b39b-fa54d445d1a5)

MacBook Pro
![image](https://github.com/user-attachments/assets/5dbfb789-3f77-4547-ab17-a78fcfdb8efd)

**Comment by jdhitsolutions** [comment]
Here's another test script.

```powershell
Param(
    [PSCredential]$Credential,
    [string]$Repo = "jdhitsolutions.com"
)
$user = $credential.UserName
$pw = $credential.GetNetworkCredential().Password
$PDSHOST = 'https://bsky.social'

#create a session
$headers = @{'Content-Type' = 'application/json' }
$body = @{
    'identifier' = $user
    'password'   = $pw
} | ConvertTo-Json

$s = Invoke-RestMethod -Uri "$PDSHOST/xrpc/com.atproto.server.createSession" -Method Post -Headers $headers -Body $body
$headers.Add('Authorization', "Bearer $($s.accessJwt)")

$apiUrl = "https://bsky.social/xrpc/com.atproto.repo.listRecords?repo=$repo&collection=app.bsky.feed.post&limit=5"

$splat = @{
    Uri                     = $apiUrl
    Method                  = 'Get'
    Headers                 = $headers
    ErrorAction             = 'Stop'
    OutVariable             = 'global:ov'
    ResponseHeadersVariable = 'global:rh'
    Verbose                 = $true
}

$r = Invoke-RestMethod @splat
$r.records.value | Select CreatedAt,Text
```

If I use your test name, this works as expected.

![image](https://github.com/user-attachments/assets/e069e4d6-a98d-40b5-b83d-e3415d523134)

But it fails with your other account name.

![image](https://github.com/user-attachments/assets/40f82da5-13f8-4439-b6c7-d2b28a0c649f)

However, I can get your DiD ( did:plc:6sa7bzdm7behw6k45oaprg7f) from your profile, and that WILL work.

![image](https://github.com/user-attachments/assets/13a87b06-943d-46fb-ad72-16c9eb178f46)

There is something about the `com.atproto.repo` endpoint that can't resolve `matthewrstreeter`.

**Comment by jdhitsolutions** [comment]
Try my test repo list script on both systems testing both account names and the DID of your DNS account and see if you get the same results I do.

**Comment by jdhitsolutions** [comment]
I'm getting some guidance from the Bluesky developer's Discord. I may need to revise my code to use the DiD instead of an account handle.

**Comment by jdhitsolutions** [comment]
Holding off on any more testing until Bluesky's network issues are resolved.

**Comment by matthewstreeter** [comment]
Did I break everything haha 😆 /s

**Comment by jdhitsolutions** [comment]
I made a major change to the posting command in the latest version. Update to v1.3.0 and let's see if this makes a difference.

**Comment by matthewstreeter** [comment]
Success!

![image](https://github.com/user-attachments/assets/fe569f0e-2267-4057-98dd-9f426958eefc)

**Comment by jdhitsolutions** [comment]
Excellent. It appears some API endpoints don't work well with handles so I revised commands to use the accounts DID where it was supported.
