### ISSUE TITLE
Notification Mention Alert

### ISSUE THREAD

**Issue by matthewstreeter** [jdhitsolutions/PSBluesky#19]
I have noticed that the recipient is not alerted with a Notification after typing @username.

I tried a few times now from my primary account and my test account with the same results. 
- When I send a PSBluesky module post with a message that includes @username, the recipient does not get a new notification alert of this
- When I send a post from the website or mobile app with a message that includes @username, the recipient gets a new notification alert of this

If you look at the URL links from the two posts.
- URL from PSBluesky: https://bsky.app/profile/matthew-test.bksy.social
- URL from Website @mention: https://bsky.app/profile/did:plc:szpos4lod4aqu65tiartb42g

![Screenshot 2024-11-15 at 8 48 08 PM](https://github.com/user-attachments/assets/297914d1-3da4-4ba7-a684-998eed2be35e)
![image](https://github.com/user-attachments/assets/63d7b83d-148d-4c38-a707-fda7c1adb5df)

**Comment by jdhitsolutions** [comment]
I'll have to see if there is a difference between formatting a mention and a notification.  I just sent this:

```powershell
PS C:\> skeet "Testing #PowerShell notifications with the PSBluesky module to @jdhitsolutions.com and @matthewrstreeter.com"
https://bsky.app/profile/did:plc:ohgsqpfsbocaaxusxqlgfvd7/post/3lb36hohbbb2q
```

The post properly formats the mentions.

![image](https://github.com/user-attachments/assets/307990bd-de0b-423e-b65c-e7440a52980e)

But I see now that it never gets triggered as a notification.

**Comment by jdhitsolutions** [comment]
I see the issue. I think I'm only creating an inline link facet and not a notification

![image](https://github.com/user-attachments/assets/984294e6-4b78-4905-b86f-1ffced176cd8)

**Comment by jdhitsolutions** [comment]
Update to v2.0.0 of the module and verify this works now.

**Comment by matthewstreeter** [comment]
Looks like that worked! Many thanks!
